### ISSUE TITLE
install，run error

### ISSUE THREAD

**Issue by wwb568109135** [taoeffect/vue-script2#15]
main.js
import Vue from 'vue'
import Demo from './Demo'

Vue.config.productionTip = false

var x = require('vue-script2')
console.log(x)
Vue.use(x)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  render: h => h(Demo)
})

-------------
error

浏览器控制台（chrome  console）

vipClub.vue?9a8b:164 Uncaught ReferenceError: VueScript2 is not defined
    at Object.eval (vipClub.vue?9a8b:164)
    at eval (1018:319)
    at Object.<anonymous> (app.js:7155)
    at __webpack_require__ (app.js:706)
    at fn (app.js:112)
    at eval (vipClub.vue?effb:1)
    at Object.<anonymous> (app.js:6989)
    at __webpack_require__ (app.js:706)
    at fn (app.js:112)
    at eval (lvshou.js?a593:1)
(anonymous) @ vipClub.vue?9a8b:164
.....

How do it for me？

**Comment by taoeffect** [comment]
You seem to be calling `VueScript2` in `vipClub.vue` without requiring.

**Comment by wwb568109135** [comment]
in  vipClub.vue  page

you  mean：

js
var VueScript2 ＝ require('vue-script2')

？？

**Comment by taoeffect** [comment]
Yes, you need to have that in there. If it is and it's not getting set for some reason (which is what the error message is saying), then it could be some issue with webpack or something. I don't know, but it's not an issue with vue-script2.
