### ISSUE TITLE
work without using vue-router? where to put script2? MIME type error

### ISSUE THREAD

**Issue by Rob-Rychs** [taoeffect/vue-script2#16]
Hi,

some quick questions: 

1. Is it possible to use vue-script2 without vue-router?

2. Where do we put the <script2> tags in the .vue element that we are trying to load extra script tags onto (like` jquery` for example) ? in the <template> tag? in the <script>tag ? outside both of those above the <style> tag?

3. I'm currently getting an error: `Refused to execute script from 'http://127.0.0.1:4000/asesets/js/lib/imagesloaded.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`
Any ideas on why? the script2 tag is being loaded with type="text/javascript"? i'm wondering if this could an issue with my environments buildpack but not sure....

**Comment by taoeffect** [comment]
> Is it possible to use vue-script2 without vue-router?

Yes, of course.

> Where do we put the tags in the .vue element that we are trying to load extra script tags onto (likejquery for example) ? in the tag? in the <script>tag ? outside both of those above the <style> tag?

the `<script>` (if you're using `script2ify`, otherwise `<script2>`) tags go into the `<template>` section. See the readme for details.

> I'm currently getting an error: Refused to execute script from 'http://127.0.0.1:4000/asesets/js/lib/imagesloaded.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Have a close read through the readme. You need to use `<script2>` not `<script>`, unless you're using the `script2ify` transform with browserify.

Does that help? If so please close this issue.

**Comment by Rob-Rychs** [comment]
Thanks!
