### ISSUE TITLE
document.referrer when loaded

### ISSUE THREAD

**Issue by smakinson** [taoeffect/vue-script2#19]
I'm loading a 3rd party script it checks document.referrer when it runs. It seems they are unable to get the proper referrer. Should they be able to get that properly from a VueScript2.load() call? I wait until the promise resolves before calling their setup function.

**Comment by taoeffect** [comment]
I don't know, does the problem also exist with [loadjs](https://github.com/muicss/loadjs)?

**Comment by smakinson** [comment]
Ya see the same with loadjs. Turns out I see the same not loading it this way at all, so you can probably close this.
