### ISSUE TITLE
Bug with entities

### ISSUE THREAD

**Issue by andrispraulitis** [taoeffect/vue-script2#24]
Hi, I'm using script2 directly in html files, but having a problem with entities where for example if (1 > 0) becomes if (1 & gt; 0) which of course breaks javascript.

Is there a fix for this?

**Comment by taoeffect** [comment]
It's not clear to me what's going on, can you provide more info on what exactly you're doing?

**Comment by andrispraulitis** [comment]
<img width="293" alt="screen shot 2018-05-29 at 10 27 23" src="https://user-images.githubusercontent.com/8721800/40650382-0c88d464-632b-11e8-8d78-65ec5ab28197.png">

<img width="182" alt="screen shot 2018-05-29 at 10 28 11" src="https://user-images.githubusercontent.com/8721800/40650387-113bd11e-632b-11e8-8515-71efd19f23c3.png">

**Comment by taoeffect** [comment]
Thanks for reporting this @andrispraulitis! I'll have to look at what's going on when I get a chance.

**Comment by andrispraulitis** [comment]
Hi @taoeffect, have you had a chance to look into this?

**Comment by andrispraulitis** [comment]
This is the problem: [innerHtml](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML)

Do you think replacing with textContent could fix the problem?
