### ISSUE TITLE
help about js file 404

### ISSUE THREAD

**Issue by hjy93** [taoeffect/vue-script2#34]
which I want to do is throw an old html page into this vue project.
```html
<!--example3.html file-->
<div style="color: red;">
    I am a html file container script
    <script2 src="../1.js"></script2>
</div>
```
```javascript
<!--1.js file-->
var App = function () {
    console.log('1.js run')
}

App();
```
project structure
![image](https://user-images.githubusercontent.com/31340809/51364551-7d2fe780-1b17-11e9-8844-5c60c7a4ab91.png)

thanks for your help!

**Comment by bignamehere** [comment]
Just guessing, but you need the `1.js` file accessible to where the application is running. I don't see a `1.js` file in your `dist` directory, so your path within the application should be relative to what is in `dist`, not `src`.

**Comment by zero2hj** [comment]
thanks for you help, but this issue has really gone out of my mind. I will just let it go. thanks again.
