### ISSUE TITLE
When the project is packaged   ERROR in static/js/vendor.929692407d1edd33c730.js from UglifyJs Unexpected token: punc (() [./~/_vue-script2@2.1.0@vue-script2/dist/vue-script2.js:20,0][static/js/vendor.929692407d1edd33c730.js:33339,11]

### ISSUE THREAD

**Issue by YouquanWang** [taoeffect/vue-script2#37]

**Comment by smakinson** [comment]
I am seeing an error in IE11 now, perhaps the same as this issue.  Here are a couple of screen grabs. Could it be related to move to terser?

![Screen Shot 2019-08-12 at 4 50 34 PM](https://user-images.githubusercontent.com/16784/62897599-a3221100-bd21-11e9-9247-6748c177ed6d.png)

![Screen Shot 2019-08-12 at 4 50 58 PM](https://user-images.githubusercontent.com/16784/62897623-aae1b580-bd21-11e9-9523-f5ee1a8aff27.png)

**Comment by taoeffect** [comment]
https://github.com/taoeffect/vue-script2/issues/38#issuecomment-521748148
