### ISSUE TITLE
Transpile doesn't work

### ISSUE THREAD

**Issue by cliffordh** [taoeffect/vue-script2#39]
I am trying to transpile vue-script2 inside of a Nuxt application in order to support IE11. I am using vue-google-adsense and vue-script2 is a dependency. However, even in Chrome I'm receiving this error when transpiling: "Unknown custom element: <script2>".

Any suggestions on how I can make vue-script2 compatible with IE11?

**Comment by taoeffect** [comment]
> Any suggestions on how I can make vue-script2 compatible with IE11?

https://github.com/taoeffect/vue-script2/issues/38#issuecomment-521748148
