### ISSUE TITLE
IE 11 Expected ':'

### ISSUE THREAD

**Issue by awg-cconway** [taoeffect/vue-script2#44]
When using this in my app, it seems to get stuck on IE 11 with the message `Expected ':'` with a link to the code that points here
```
// keys are the scripts that is loading or loaded, values are promises
install(Vue) { <--- Here
    if (Script2.installed) return;
```
My code works on other browsers I have tested, (chrome, firefox). But this halts my code in IE11. Any ideas on this?

**Comment by taoeffect** [comment]
IE11 not supported or encouraged.
