### ISSUE TITLE
Thank you so much for creating this! 

### ISSUE THREAD

**Issue by sahrizvi** [taoeffect/vue-script2#8]
Hello @taoeffect ! 
I just wanted to express my gratitude for this library.
This has been incredibly useful, not just because it supports the obvious case where one wants to load vendor scripts on demand, but also because there are cases where one is using legacy code which cannot be used via webpack easily (an example being a file of type "text/paperscript",  a paper.js hack). 
Additionally, the ordered loading has been really helpful to me since I have some dependency order in my legacy scripts, to get around which I'd probably need a PhD in webpack. 
I believe this is a really well thought out library, at least from a developer ergonomics perspective and it ties closely with Vue's developer friendly approach.

Feel free to close this if you want, as this is really a non issue. :-)

**Comment by taoeffect** [comment]
You're very welcome! Thank you for stopping by and saying 'thanks', it means a lot! 😄

**Comment by sahrizvi** [comment]
😊

**Comment by taoeffect** [comment]
As I mainly use browserify, I'm also curious how (or if) you do anything similar [to the `script2ify` example I give](https://github.com/taoeffect/vue-script2#writing-script-instead-of-script2-using-script2ify) (to restore normal `<script>` usage).

If you do please share; I can update the readme so that others who use Webpack can benefit. :)

**Comment by sahrizvi** [comment]
Currently, I do not do anything to convert the <script2> to <script>.
I think it just works, and is not worth the extra effort at this stage of my project.
However, if I end up doing something for this, I'd certainly share here. 
One way I am customising the library is by adding some more attributes to the script2 tag. In fact I wanted to add support for data-attributes on the script2 tag, but was not sure if you would like that to be a part of the library. 
For now, I've just monkey-patched the library with support for my custom attribs. :-)

**Comment by simondib** [comment]
Just stopping by to drop a bundle of thanks also! Looks like this is exactly what we're after. 👍
