### ISSUE TITLE
Safari 9 cross-origin

### ISSUE THREAD

**Issue by dbeaman** [taoeffect/vue-script2#9]
I know that there was a recent fix to the cross-origin issue, and I have checked that my package is up to date.
Everything works great except on  safari 9 it doesn't work,  and I get the following error:

>  [Error] Cross-origin script load denied by Cross-Origin Resource Sharing policy.
> 	(anonymous function) (vue-script2.js:102)
> 	Promise ([native code], line 0)
> 	load (vue-script2.js:73)
> 	a (vue-script2.js:49)
> 	PromiseResolutionHandlerFunction ([native code], line 0)

I've tried loading inside script2 tag with and without crossorigin="anonymous"
```
      <script2 src="//s7.addthis.com/js/300/addthis_widget.js" crossorigin="anonymous" type="text/javascript"></script2>
      <script2>
        console.log('vue2script')
        addthis.button('.addthis_btn')
      </script2>
```
In safari the rendered html looks like this:
```
<script src="//s7.addthis.com/js/300/addthis_widget.js" type="text/javascript" crossorigin="anonymous"></script>``
```

Is safari 9 not supported? any insight would be very helpful!
thanks

**Comment by taoeffect** [comment]
I don't know much about that attribute, but have you tried this in just a plain old regular HTML file (e.g. eliminating Vue as a culprit)?

**Comment by taoeffect** [comment]
Closing since I haven't heard back.

**Comment by mingchuno** [comment]
I have the same issue on Safari 9
